# Generated by Django 3.2.5 on 2021-08-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=250, null=True),
        ),
    ]
